### ISSUE TITLE
Error no module weblogolib or coreBio

### ISSUE THREAD

**Issue by souptonuts** [harmslab/phagedisplay#25]
When I run test-run.sh I get an error about no module weblogolib and corebio

I installed python weblogo using pip.  It doesn't provide weblogolib or coreBio modules.  

A google search turned up a legacy weblogo from ncbi but the ftp site isn't working.  I can copy/paste source code from webpage but there must be a better way.

**Comment by harmsm** [comment]
Duplicate of issue #24.  Closing.
